# Generated by Django 3.2 on 2022-06-25 06:10

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("deletion_datetime", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=400)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "items",
                "ordering": ["-creation_datetime"],
            },
            managers=[
                ("_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
